### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by Habbie** [dmachard/pdns-protobuf-receiver#4]
Hello! I'm Peter and I work for PowerDNS. I'm not a lawyer and I am not here to tell you to 'cease and desist' or anything that brutal.

However, we noticed an 'Intent To Package' this tool for Debian (https://salsa.debian.org/debian/pdns-logger), which currently would mean a package 'pdns-logger' would appear in Debian. This name is -very- generic, and doesn't even cover that it is 'just' a protobuf consumer, not anything related to the actual logging PowerDNS does, for example.

Would you be open to talking about a change to a more descriptive name, preferably before this name makes it into the Debian archives?

If you prefer, you can find us on IRC (irc.oftc.net #powerdns, my nickname is Habbie), or email me at peter.van.dijk@powerdns.com

Thanks!

**Comment by xtaran** [comment]
Will wait with any upload to Debian until it's clear how this will end up. I've got also no issue renaming the git repo on Salsa accordingly.

**Comment by xtaran** [comment]
Dear @Habbie:

> it is 'just' a protobuf consumer, not anything related to the actual logging PowerDNS does, for example.

I beg to disagree: As far as I understand the code, it's quite PowerDNS-specific as it only works for protobuf data with PowerDNS's protobuf data format. See e.g. https://github.com/dmachard/pdns-logger/blob/master/pdns_logger/receiver.py#L13-L16

If I understand it right, later code lines in that file also seem to refer to definitions made in that `dnsmessage.proto` file. Might be though not that much work to extend it towards being able to parse dnstap messages, too, which IIRC are also protobuf-based.

It being PowerDNS-specific is one of the reasons why I want to package it: I need a proper receiver for PowerDNS's protobuf log format. (I'm aware of https://github.com/PowerDNS/pdns/blob/master/contrib/ProtobufLogger.py, but it is not in any of the `pdns-*` Debian packages and also doesn't feature forwarding the transformed messages over the network. Additionally that file seems quite outdated given that it has `#!/usr/bin/env python2` in its shebang line—as Python 2 is EoL since beginning of 2020.)

The fact that it uses Protobuf and is primarily a log receiver could though be better reflected in the project name indeed. Maybe something like "pdns-protobuf-log-receiver" or "pdns-protobuf-log-collector"? Must though admit that those propositions are already rather clunky with each having four words. Maybe "protobuf" can be shortened to "pb" and we could spare one dash, then we would be at "pdns-pblog-receiver" or "pdns-pblog-collector". Maybe even drop the "log" completely since it's a bit implied by "pdns" and "protobuf" resp. "pb" and some people might parse "pblog" as "p" and "blog": "pdns-pb-receiver", "pdns-pb-collector", "pdns-protobuf-receiver" or "pdns-protobuf-collector".

**Comment by Habbie** [comment]
> it is 'just' a protobuf consumer, not anything related to the actual logging PowerDNS does, for example.

Sorry, yes, it is very much PowerDNS specific (and I think it would make sense to reflect that in the name); it's 'logger' that is overly generic :)

**Comment by Habbie** [comment]
> Might be though not that much work to extend it towards being able to parse dnstap messages, too, which IIRC are also protobuf-based.

Indeed, and PowerDNS can emit those too (as can Unbound and other products).

**Comment by Habbie** [comment]
> as Python 2 is EoL since beginning of 2020

We are (very slowly) getting rid of all our Python 2 code, but for now that script does work.

**Comment by Habbie** [comment]
> "pdns-protobuf-receiver" or "pdns-protobuf-collector".

I like these two :)

**Comment by xtaran** [comment]
> Sorry, yes, it is very much PowerDNS specific (and I think it would make sense to reflect that in the name); it's 'logger' that is overly generic :)

Thanks for that clarification!

**Comment by dmachard** [comment]
Hi, 

Just to be clear, I made this package just for fun and by curiosity for the protobuf protocol and powerdns's products.

In fact, I wondered if I will kept this project or not, because I am working on another project (generic one) which is not specific to powerdns (https://github.com/dmachard/dnstap-receiver).

So, in my side, the project can be renamed, or completely removed... , as you want.

Denis

**Comment by dmachard** [comment]
by the way +1 for pdns-protobuf-receiver

**Comment by Habbie** [comment]
> So, in my side, the project can be renamed, or completely removed... , as you want.

We (PowerDNS) would be happy to adopt the project into our organisation. Would that work for you?

**Comment by dmachard** [comment]
it will be great :)
I renamed the project

**Comment by xtaran** [comment]
I updated the name of the packaging git repo accordingly, too: https://salsa.debian.org/debian/pdns-protobuf-receiver/

Will update the packaging soon, too.

**Comment by Habbie** [comment]
>  I renamed the project

Awesome! Do you want to transfer the repository to the PowerDNS organisation?

**Comment by Habbie** [comment]
@xtaran just fyi, the repository has been transferred to us (PowerDNS) now

@dmachard thanks!

**Comment by xtaran** [comment]
> @xtaran just fyi, the repository has been transferred to us (PowerDNS) now

Thanks for the heads up! I actually thought that will not happen because @dmachard's "close #4" still came in the notification mail with his account in the repo name. But maybe that was also a Github caching glitch or so.

**Comment by Habbie** [comment]
> But maybe that was also a Github caching glitch or so.

I got the right subject after the name change.. maybe threading in your mail client confused you?
